Traceback (most recent call last):
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 806, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['import numpy as np', 'import matplotlib.pyplot as plt', 'from sklearn.linear_model import LinearRegression', 'from sklearn.metrics import mean_squared_error', '']
...
['plt.show()', '', 'print(f"Fitted slope: {model.coef_[0][0]:.2f}")', 'print(f"Fitted intercept: {model.intercept_[0]:.2f}")', 'print(f"Mean Squared Error: {mse:.2f}")']
-------------------

